## Basic Configuration

baseurl = "https://wangsong.site/"
builddrafts = false
canonifyurls = false
languageCode = "zh_CN"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "小松"
title = "小松的学习笔记"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Rieux"
intro = ""
description = "对未来的真正慷慨，是把一切献给现在。"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "ws1603"
email = "18388866683@163.com"

## Extras
[params.extra]
copyright = "© 2019. 小松. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "posts"
    weight = 100
    identifier = "blog"
    url = "./posts/"

[[menu.main]]
    name = "notes"
    identifier = "notes"
    weight = 200
    url = "./notes"

[[menu.main]]
    name = "problems"
    identifier = "problems"
    weight = 300
    url = "./problems/"

[[menu.main]]
    name = "leetcode-log"
    identifier = "leetcode-log"
    weight = 400
    url = "./leetcode-log/"

