title = "小松的博客"
theme = "solar-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-light" # solarized-light, -dark or -dark256
copyright = ""

[params]
  scheme = "gray" # light, dark, gray or preference
  description = "A wizard is never late"

[menu]
  [[menu.main]]
    name = "Home"
    url = "https://wangsong.site/"
  [[menu.main]]
    name = "About"
    url = "https://wangsong.site/"
